build: 整理插件构建、自动推送到设备端的方法
MZ-FE/vue-webpack-weex pull request #17
Opened 2023-02-03 05:39 UTC by kevinsheep

1，增加对Linux/IOS推送的方法，自适应Linux及Windows路径的差别，微调推送指令
2，增加打包过程的提示信息

2023-02-03 05:40 UTC, kevinsheep commented
#17

2023-02-03 05:57 UTC, Wyatex commented on build/push.js
> +const { PUSH_AFTER_DONE, SN8_OR_A0_LIST, PLUGIN_TYPE } = env
这里`PUSH_AFTER_DONE`好像用的.env配置，.env是不是忘记push上来了

2023-02-03 05:57 UTC, Wyatex commented on build/utils.js
> +  return pkg.version
改成`return require('../package.json').version`会不会好一点

2023-02-04 08:44 UTC, Wyatex requested changes

2023-02-04 08:44 UTC, Wyatex commented on build/push.js
> +  '/run/user/1000/gvfs/afc:host=78d1f717dc0fe15fd6209e461892fad9cc356a49,port=3' // 不同系统或设备有差异时修改此处
这个放到.env应该会好一点

2023-02-04 09:02 UTC, merged